logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: spring-kubernetes-configmap

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health